# basic tmux config

set -g mouse on
set -g history-limit 10000
set -g base-index 1

setw -g pane-base-index 1

# faster escape time
set -sg escape-time 10

# 256 color support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# reload config without restarting
bind r source-file ~/.tmux.conf \; display "tmux config reloaded"
